var response_ok = {
  'login': 'GrahamCampbell',
  'id': 2829600,
  'avatar_url': 'https://avatars.githubusercontent.com/u/2829600?v=3',
  'gravatar_id': '',
  'url': 'https://api.github.com/users/GrahamCampbell',
  'html_url': 'https://github.com/GrahamCampbell',
  'followers_url': 'https://api.github.com/users/GrahamCampbell/followers',
  'following_url': 'https://api.github.com/users/GrahamCampbell/following{/other_user}',
  'gists_url': 'https://api.github.com/users/GrahamCampbell/gists{/gist_id}',
  'starred_url': 'https://api.github.com/users/GrahamCampbell/starred{/owner}{/repo}',
  'subscriptions_url': 'https://api.github.com/users/GrahamCampbell/subscriptions',
  'organizations_url': 'https://api.github.com/users/GrahamCampbell/orgs',
  'repos_url': 'https://api.github.com/users/GrahamCampbell/repos',
  'events_url': 'https://api.github.com/users/GrahamCampbell/events{/privacy}',
  'received_events_url': 'https://api.github.com/users/GrahamCampbell/received_events',
  'type': 'User',
  'site_admin': false,
  'name': 'Graham Campbell',
  'company': 'University of York',
  'blog': 'https://gjcampbell.co.uk/',
  'location': 'The United Kingdom',
  'email': 'graham@alt-three.com',
  'hireable': true,
  'bio': 'PHP Ninja | Open Source | Laravel | StyleCI | Cachet | University of York',
  'public_repos': 25,
  'public_gists': 0,
  'followers': 2192,
  'following': 60,
  'created_at': '2012-11-18T22:14:00Z',
  'updated_at': '2016-09-09T18:39:26Z'
};
